sudo: false
cache: bundler
language: ruby
bundler_args: --quiet
script:
  - bundle exec rake
rvm:
  - 2.6.5
services:
  - postgresql
  - mysql
env:
  matrix:
    - SOLIDUS_BRANCH=v2.9 DB=postgres
    - SOLIDUS_BRANCH=v2.10 DB=postgres
    - SOLIDUS_BRANCH=v2.11 DB=postgres
    - SOLIDUS_BRANCH=master DB=postgres
    - SOLIDUS_BRANCH=v2.9 DB=mysql
    - SOLIDUS_BRANCH=v2.10 DB=mysql
    - SOLIDUS_BRANCH=v2.11 DB=mysql
    - SOLIDUS_BRANCH=master DB=mysql
